---

- name: Configure System prereq
  hosts: nifi_cluster
  roles:
    - nifi/prereqs/init_conf
  tags:
    - prereqs

- name: Install Java and downlaod nifi packages
  hosts: nifi_cluster
  roles:
    - nifi/prereqs/os
  tags:
    - os

- name: Setup NiFi Cluster et ZooKeeper
  hosts: nifi_cluster
  become: yes
  gather_facts: yes
  vars:
    nifi_single_node: False
    nifi_version: "2.0.0-M4"  # Version mise à jour pour NiFi
    #zookeeper_version: "3.8.4"  # Version mise à jour pour ZooKeeper
    nifi_state_management_embedded_zookeeper_start: True # Utilisation du Zookeeper intégré avec la solution Nif

  roles:
    - role: nifi/deployement
      nifi_major_version: "{{ nifi_version }}"
      nifi_zookeeper_servers: "{{ groups['zookeeper-nodes'] }}"