    nifi-nodes:
     hosts:      
     nifi-01:       
     ansible_host: r-inf-nifi-01.hop.air
       fqdn: rct-nifi-01.hop.fr
        nifi-02:
         ansible_host: r-inf-nifi-02.hop.air
            fqdn: rct-nifi-02.hop.fr
               children:    
                zookeeper-nodes:
                     hosts:    
                        zookeeper-01:           
                           ansible_host: r-inf-zkpr-01.hop.air
                                      fqdn: rct-zookeeper-01.hop.fr
                                        zookeeper-02:           
                                           ansible_host: r-inf-zkpr-02.hop.air
                                                    fqdn: rct-zookeeper-02.hop.fr
                                                           zookeeper-03:           
                                                              ansible_host: r-inf-zkpr-03.hop.air
                                                               fqdn: rct-zookeeper-03.hop.fr 
