---
- name: Download NiFi binaries
  ansible.builtin.get_url:
    url: "https://archive.apache.org/dist/nifi/{{ nifi_version }}/nifi-{{ nifi_version }}-bin.zip"
    dest: /tmp/nifi-{{ nifi_version }}-bin.zip

- name: Extract NiFi binaries
  ansible.builtin.unarchive:
    src: /tmp/nifi-{{ nifi_version }}-bin.zip
    dest: /opt/
    remote_src: yes
    extra_opts: [ -n ]

# - name: Ensure Java 21 is installed
#   ansible.builtin.apt:
#     name: openjdk-21-jre
#     state: present
#     update_cache: yes

- name: Install necessary dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - curl
    - wget
    - net-tools
    - vim
    - telnet
    - bind-utils
    - unzip
    - screen
    - mlocate
